apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot
  labels:
    app: kbot
spec:
  selector:
    matchLabels:
      app: kbot
  template:
    metadata:
      name: kbot
      labels:
        app: kbot
    spec:
      containers:
      - env:
        - name: TELE_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: kbot
        image: denvasyliev/kbot:v2.0.12
        imagePullPolicy: IfNotPresent
        name: kbot
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/mem
          name: dev-mem
      volumes:
      - hostPath:
          path: /dev/mem
          type: ""
        name: dev-mem