apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot
spec:
  template:
    spec:
      containers:
        - name: kbot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"