name: KBOT-CI

on: 
  push:
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v1
        
      - name: d login
        if: "success() && github.ref == 'refs/heads/develop' "
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Declare SHA vars to use on other actions
        id: vars
        shell: bash
        run: |
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "::set-output name=sha_short::${GITHUB_SHA::7}"
        
      - name: d build
        uses: docker/build-push-action@v1
        if: "success() && github.ref == 'refs/heads/develop' "
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: den-vasyliev/kbot
          path: ./
          tags: latest-${{ steps.vars.outputs.sha_short }}
          dockerfile: Dockerfile
          
      - name: update current version
        uses: mikefarah/yq@3.3.2
        if: "success() && github.ref == 'refs/heads/develop' "
        with: 
          cmd: yq w -i kbot-helm/values.yaml image.tag latest-${{ steps.vars.outputs.sha_short }}
        
      - name: setup git config
        if: "success() && github.ref == 'refs/heads/develop' "
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add kbot-helm/values.yaml
          git commit -m "update code version to ${{ steps.vars.outputs.sha_short }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
        