name: KBOT-CI

on: 
  push:
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: "success() && github.ref == 'refs/heads/develop' "
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Declare SHA vars to use on other actions
        id: vars
        shell: bash
        run: |
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "::set-output name=sha_short::${GITHUB_SHA::7}"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            ghcr.io/den-vasyliev/kbot:latest-${{ steps.vars.outputs.sha_short }}
      - run: docker push ghcr.io/den-vasyliev/kbot:latest-${{ steps.vars.outputs.sha_short }}         
          
      - name: update current version
        uses: mikefarah/yq@3.3.2
        if: "success() && github.ref == 'refs/heads/develop' "
        with: 
          cmd: yq w -i kbot-helm/values.yaml image.tag latest-${{ steps.vars.outputs.sha_short }}
        
      - name: setup git config
        if: "success() && github.ref == 'refs/heads/develop' "
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add kbot-helm/values.yaml
          git commit -m "update code version to ${{ steps.vars.outputs.sha_short }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
        
